### ISSUE TITLE
Duda en  teoria/Tema_4/T_4_4_Clases_Abstractas/main.cpp

### ISSUE THREAD

**Issue by vrivas** [POOUJA/teoria#1]
Hola.
Estaba viendo un poco los ejemplos del resto de temas, y no sé por qué se hace linea=linea+... en la siguiente función... aunque con lo poco que duermo últimamente, lo raro es que sepa por qué si se hace todo lo demás :)

<pre> 
template<class T>
bool GuardaCSV(T* elementos[], int numElementos, std::string nombreFichero ) {
    std::ofstream f;
    std::string linea;
    bool guardado=false;
    f.open(nombreFichero.c_str());
    if (f.good()) {
        for ( int i=0; i&lt;numElementos; i++ ) {
            //Polimorfismo de métodos usando la interfaz ItemCSV
           <strong>___ linea=linea+elementos[i]->toCSV(); ____</strong>
            f << linea << std::endl;
        };
        f.close();
        guardado=true;
    }
    return guardado;
}
</pre>

**Comment by jrbalsas** [comment]
Fixed, thx!
