### ISSUE TITLE
En cuanto a los nombres de las funciones

### ISSUE THREAD

**Issue by vrivas** [POOUJA/teoria#2]
Hola de nuevo.
Veo que JR comienza las funciones en mayúsculas, aunque no los métodos.
¿Vamos a seguir todos ese convenio? Mejor dicho... ¿dijimos de hacerlo y soy el único que no lo ha hecho? :)
Gracias!

**Comment by algarcia-ujaen** [comment]
Yo estoy haciendo las funciones también empezando con minúsculas...

**Comment by jrbalsas** [comment]
Ya va siendo hora de arreglar esto ;-)

**Comment by jrbalsas** [comment]
Hecho, gracias @vrivas
